#%RAML 1.0 NamedExample
Active-APIs-Organization-Response-200:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Organization successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19
  organization:
    name: TheOrganization
    environments: 
      -
        name: Development
        apis:
          system:
            - 
              name: dev-system-api
              workerSize: 0.1
              workers: 2
              runtimeVersion: 4.2.1
          process:
            -
              name: dev-process-api 
              workerSize: 0.2
              workers: 2
              runtimeVersion: 3.9.1
          experience:
            -
              name: ApplicationThree
              workerSize: 1
              workers: 4
              runtimeVersion: 3.8.7
        totalActiveAPIs: 3
        activeSystemAPIs: 1
        activeProcessAPIs: 1
        activeExperienceAPIs: 1
      -
        name: QA
        apis:
          system:
            - 
              name: qa-system-api
              workerSize: 0.1
              workers: 2
              runtimeVersion: 4.2.1
          process:
            -
              name: qa-process-api
              workerSize: 0.2
              workers: 2
              runtimeVersion: 3.9.1
          experience:
            -
              name: qa-expeience-api
              workerSize: 1
              workers: 4
              runtimeVersion: 3.8.7
        totalActiveAPIs: 3
        activeSystemAPIs: 1
        activeProcessAPIs: 1
        activeExperienceAPIs: 1
    totalActiveAPIs: 6