#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: API versions successfully retrieved for organization.
    transactionId: 826fb9e0-d32d-11e9-85a1-f01898500623
    timestamp: 2019-09-09T12:13:27.372-06:00
  environment:
    name: Development
    id: 9fe156aa-5b63-450c-8e20-ad065dd12d80
    moreThanOneVersionPercentage: 25.0%
    avgNumberOfVersions: "1.25"
    apis:
      -
        assetId: major-api-version
        id: 15719175
        organizationId: 85720984-fa27-4bbd-8213-5ecac9e8d93e
        environmentId: 9fe156aa-5b63-450c-8e20-ad065dd12d80
        versions:
           - "1.0.0"
           - "2.0.0"
      -
        assetId: anypoint-kpi-system-api
        id: 15679813
        organizationId: 85720984-fa27-4bbd-8213-5ecac9e8d93e
        environmentId: 9fe156aa-5b63-450c-8e20-ad065dd12d80
        versions:
          - "2.0.0"
          - "1.0.3"
           
      -
        assetId: minor-version-api
        id: 15718483
        organizationId: 85720984-fa27-4bbd-8213-5ecac9e8d93e
        environmentId: 9fe156aa-5b63-450c-8e20-ad065dd12d80
        versions:
          - "1.0.1"
