#%RAML 1.0 NamedExample
API-Status-Response-504:
  apiStatus:
    name: Anypoint KPI System API
    status: Gateway Timeout
    statusCode: "504"
    description: Description
    link: http://anypoint.kpi.system.api/504.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19