#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: Not Found
    statusCode: "404"
    description: Description
    link: http://anypoint.kpi.system.api/404.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19