#%RAML 1.0 NamedExample
Exchange-Assets-Ratings-Response-200:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Anypoint Exchange asset ratings successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: 3c2b3590-0a10-11e9-a7d4-f01898500623
    timestamp: 2019-01-02T14:06:58.611-07:00
  assets:
    - 
      assetId: common-logging
      type: template
      name: Mule common-logging Application
      status: published
      rating: 0
      numberOfRates: 0
    - 
      assetId: sync-exception-handling
      type: template
      name: Mule sync-exception-handling Application
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: async-exception-handling
      type: template
      name: Mule async-exception-handling Application
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: async-api-template
      type: template
      name: Mule async-api-template Application
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: api-consumption-request
      type: custom
      name: API Consumption Request
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: correlation-id-api-example
      type: example
      name: Correlation ID API Example
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: redis-cache-example
      type: example
      name: Redis Cache Example
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: ping-api-example
      type: example
      name: Ping API Example
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: mulesoft-recommended-support-process
      type: custom
      name: MuleSoft Recommended Support Process
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: project-planning-workbook
      type: custom
      name: Project Planning Workbook
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: training-and-enablement-plan
      type: custom
      name: Training and Enablement Plan
      status: published
      rating: 0
      numberOfRates: 0
    -  
      assetId: build-and-deploy-automation-with-release-management
      type: custom
      name: Build and Deploy Automation with Release Management
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-configuration-properties-template
      type: custom
      name: API Configuration Properties Template
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: anypoint-platform-reference-architecture
      type: custom
      name: Anypoint Platform Reference Architecture
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: application-sizing-guide---cloudhub
      type: custom
      name: Application Sizing Guide - CloudHub
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: client-management-w-mule-oauth-20-provider
      type: custom
      name: Client Management w/ Mule OAuth 2.0 Provider
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: recommended-platform-kpis
      type: custom
      name: Recommended Platform KPIs
      status: published
      rating: 0
      numberOfRates: 0
    -
      assetId: mule-activemq-pubsub-api
      type: example
      name: Mule mule-activemq-pubsub Application
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: mule3-dataweave-example-api
      type: example
      name: Mule mule3-dataweave-template Application
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: oauth-client-employee-api
      type: example
      name: Mule oauth-client-employee Application
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-unit-testing-and-munit
      type: custom
      name: API Unit Testing & MUnit
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-led-connectivity-overview
      type: custom
      name: API-led Connectivity Overview
      status: published
      rating: 0
      numberOfRates: 0      
    - 
      assetId: maven-recommendations
      type: custom
      name: Maven Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-logging-recommendations
      type: custom
      name: API Logging Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: error-and-exception-handling-strategies
      type: custom
      name: Error and Exception Handling Strategies
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: mule-code-style-guide
      type: custom
      name: Mule Code Style Guide
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-caching-options
      type: custom
      name: API Caching Options
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-implementation-recommendations
      type: custom
      name: API Implementation Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: raml-recommendations
      type: custom
      name: RAML Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-versioning-recommendations
      type: custom
      name: API Versioning Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-url-recommendations
      type: custom
      name: API URL Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: api-design-recommendations
      type: custom
      name: API Design Recommendations
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: sync-api-template
      type: template
      name: Mule sync-api-template Application
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: email-validation-system-api
      type: example
      name: email-validation-system-api
      status: published
      rating: 0
      numberOfRates: 0
    -    
      assetId: sync-svc-template
      type: example
      name: Synchronous API Template
      status: published
      rating: 0
      numberOfRates: 0
  assetRatings:
    lessThanTwoFive:
      api-spec-fragment: 1 
      connector: 1
      custom: 1
      example: 1
      http-api: 1
      rest-api: 1
      soap-api: 1
      template: 1
    twoFiveToThreeFive:
      api-spec-fragment: 2
      connector: 2
      custom: 2
      example: 2
      http-api: 2
      rest-api: 2
      soap-api: 2
      template: 2 
    threeFiveToFour:
      api-spec-fragment: 3 
      connector: 3
      custom: 3
      example: 3
      http-api: 3
      rest-api: 3
      soap-api: 3
      template: 3
    fourToFourFive:
      api-spec-fragment: 4 
      connector: 4
      custom: 4
      example: 4
      http-api: 4
      rest-api: 4
      soap-api: 4
      template: 4
    greaterThanFourFive:
      api-spec-fragment: 5 
      connector: 5
      custom: 5
      example: 5
      http-api: 5
      rest-api: 5
      soap-api: 5
      template: 5