#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Organization name successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: 3c2b3590-0a10-11e9-a7d4-f01898500623
    timestamp: 2019-01-02T14:06:58.611-07:00
  organizationName: organization-name