#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Environment successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19
  environment: 
    id: 3b68677b-45f8-456b-bbd6-8edff859d1f9,
    name: Development
    type: sandbox,
    runtimeVersions: 
      -
        version: "3.8.5"
        applicationsUsing: 2
      -
        version: "3.8.3"
        applicationsUsing: 4
      - 
        version: "3.9.1"
        applicationsUsing: 7
      - 
        version: "4.1.3"
        applicationsUsing: 1
      -
        version: "3.9.0"
        applicationsUsing: 1
  totalApplications: 15