#%RAML 1.0 NamedExample
vCores-Environment-Response-200::
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Environment successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19
    timestamp: 2019-01-02T14:06:58.611-07:00
  environment:
    id: 9fe156aa-5b63-450c-8e20-ad065dd12d80 
    name: Development
    type: sandbox
    applications:
      - 
        name: ApplicationOne
        workerSize: 0.1
        workers: 2
        totalVCores: 0.2
        runtimeVersion: 4.2.1
        status: STARTED
      -
        name: ApplicationTwo
        workerSize: 0.2
        workers: 2
        totalVCores: 0.4
        runtimeVersion: 3.9.1
        status: STARTED
      -
        name: ApplicationThree
        workerSize: 1
        workers: 4
        totalVCores: 4
        runtimeVersion: 3.8.7
        status: STARTED
    totalActiveApplications: 4
    totalVCores: 4.6