#%RAML 1.0 NamedExample
value:
  - environmentName,environmentType,appName,appWorkerSize,appWorkers,runtimeVersion,status
  - Design,design,app,0.2,1,4.1.1,STARTED
  - Development,sandbox,app-system-api,0.1,1,3.9.1-AM,STARTED
  - Production,production,app-system-api,0.1,2,3.9.0,STARTED