#%RAML 1.0 NamedExample
value:
  apiStatus:
    name: Anypoint KPI System API
    status: OK
    statusCode: "200"
    description: Application successfully retrieved.
    link: http://anypoint.kpi.system.api/200.html
    transactionId: e77af5b0-9bf8-11e8-9002-c4b301c8ce19
    timestamp: 2019-01-02T14:06:58.611-07:00
  application:
    name: ApplicationOne
    workerSize: 0.1
    workers: 2
    totalVCores: 0.2
    status: STARTED
  totalVCores: 0.2